name: corpus
version: 0.1.0

description: >-
  Dart/Flutter code-mining corpus experiments

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  analyzer: '>=5.4.0 < 7.0.0'
  args: ^2.0.0
  cli_util: ^0.4.0
  collection: ^1.10.0
  meta: ^1.0.0
  path: ^1.2.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
